{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Errors and Exceptions\n",
    "\n",
    "- Types\n",
    "\t- Syntax errors\n",
    "\t- Exceptions\n",
    "\n",
    "## Syntax Errors\n",
    "\n",
    "- Parsing errors\n",
    "\n",
    "\n",
    "if True print('Hello world')\n",
    "\n",
    "\n",
    "## Exceptions\n",
    "\n",
    "- syntax is correct\n",
    "- error while execution\n",
    "\n",
    "\n",
    " 10 * (1/0)\n",
    " 4 + spam*3\n",
    " '2' + 2\n",
    "\n",
    "## Handling Exceptions\n",
    "\n",
    "while True:\n",
    "   try:\n",
    "       x = int(input(\"Please enter a number: \"))\n",
    "       break\n",
    "   except ValueError:\n",
    "       print(\"Oops!  That was no valid number.  Try again...\")\n",
    "\n",
    "### multiple exceptions\n",
    "\n",
    "except (RuntimeError, TypeError, NameError):\n",
    "\n",
    "import sys\n",
    "\n",
    "try:\n",
    "    f = open('myfile.txt')\n",
    "    s = f.readline()\n",
    "    i = int(s.strip())\n",
    "except OSError as err:\n",
    "    print(\"OS error: {0}\".format(err))\n",
    "except ValueError:\n",
    "    print(\"Could not convert data to an integer.\")\n",
    "except:\n",
    "    print(\"Unexpected error:\", sys.exc_info()[0])\n",
    "    raise\n",
    "\n",
    "## else clause\n",
    "\n",
    "- executes when no exception occurs\n",
    "\n",
    "### without else\n",
    "\n",
    "for arg in sys.argv[1:]:\n",
    "    try:\n",
    "        f = open(arg, 'r')\n",
    "\t\t# do something here which could cause an exception\n",
    "\t\tf.close() #unsure whether this will run\n",
    "    except OSError:\n",
    "        print('cannot open', arg)\n",
    "\t\t#f.close()\n",
    "\n",
    "\n",
    "### with else\n",
    "\n",
    "for arg in sys.argv[1:]:\n",
    "    try:\n",
    "        f = open(arg, 'r')\n",
    "    except OSError:\n",
    "        print('cannot open', arg)\n",
    "    else:\n",
    "        print(arg, 'has', len(f.readlines()), 'lines')\n",
    "        f.close() # this will run if no exception occurs\n",
    "\n",
    "\n",
    "## Details of the exception\n",
    "\n",
    "try:\n",
    "    raise Exception('spam', 'eggs')\n",
    "except Exception as inst:\n",
    "    print(type(inst))    # the exception instance\n",
    "    print(inst.args)     # arguments stored in .args\n",
    "    print(inst)          # __str__ allows args to be printed directly,\n",
    "                         # but may be overridden in exception subclasses\n",
    "    x, y = inst.args     # unpack args\n",
    "    print('x =', x)\n",
    "    print('y =', y)\n",
    "\n",
    "## Raising Exceptions\n",
    "\n",
    "- force an exception to occur. \n",
    "- Alternate to returning error codes\n",
    "- goes back up the hierarchy of function calls\n",
    "\n",
    "\n",
    "raise NameError('HiThere')\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "NameError: HiThere\n",
    "\n",
    "## User-defined Exceptions\n",
    "\n",
    "class Error(Exception):\n",
    "\t\"\"\"Base class for exceptions in this module.\"\"\"\n",
    "\tpass\n",
    "\n",
    "class InputError(Error):\n",
    "\t\"\"\"Exception raised for errors in the input.\n",
    "\n",
    "\tAttributes:\n",
    "\t\texpression -- input expression in which the error occurred\n",
    "\t\tmessage -- explanation of the error\n",
    "\t\"\"\"\n",
    "\n",
    "\tdef __init__(self, expression, message):\n",
    "\t\tself.expression = expression\n",
    "\t\tself.message = message\n",
    "\n",
    "class TransitionError(Error):\n",
    "\t\"\"\"Raised when an operation attempts a state transition that's not\n",
    "\tallowed.\n",
    "\n",
    "\tAttributes:\n",
    "\t\tprevious -- state at beginning of transition\n",
    "\t\tnext -- attempted new state\n",
    "\t\tmessage -- explanation of why the specific transition is not allowed\n",
    "\t\"\"\"\n",
    "\n",
    "\tdef __init__(self, previous, next, message):\n",
    "\t\tself.previous = previous\n",
    "\t\tself.next = next\n",
    "\t\tself.message = message\n",
    "\n",
    "## Defining Clean-up Actions. Finally clause\n",
    "\n",
    "- Runs regarless of try/except\n",
    "\n",
    "\n",
    "try:\n",
    "    raise KeyboardInterrupt\n",
    "finally:\n",
    "    print('Goodbye, world!')\n",
    "\n",
    "def divide(x, y):\n",
    "\ttry:\n",
    "\t    result = x / y\n",
    "\texcept ZeroDivisionError:\n",
    "\t    print(\"division by zero!\")\n",
    "\telse:\n",
    "\t    print(\"result is\", result)\n",
    "\tfinally:\n",
    "\t    print(\"executing finally clause\")\n",
    "\n",
    "divide(2, 1)\n",
    "\n",
    "As you can see, the finally clause is executed in any event. The TypeError raised by dividing two strings is not handled by the except clause and therefore re-raised after the finally clause has been executed.\n",
    "\n",
    "- useful for releasing external resources (such as files or network connections)\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
